name: Fetch Data

on:
  workflow_dispatch:
  schedule:
    - cron:  '30 11 * * *'

permissions:
  actions: write
  checks: write
  contents: write
  pull-requests: write

jobs:
  fetch_data:
    runs-on: ubuntu-latest
    env:
      API_KEY: ${{ secrets.ODDS_API_KEY }}
      PROJECT_ROOT: ${{ github.workspace }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run fetch_data script
      run: python src/fetch_data.py

    - name: Commit and push if changed
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        timestamp=$(date -u)
        git commit -m "Automated data update $timestamp" || exit 0

    - name: Push changes
      run: |
        git push origin data-update-branch

    - name: Create Pull Request
      uses: repo-sync/pull-request@v2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        pr_title: "Automated data update"
        pr_body: "Update data files"
        pr_label: "automated-pr"
        pr_allow_empty: false  # Change to true if you want to allow empty PRs

    - name: Approve Pull Request
      run: |
        pr_number=$(gh pr list --base main --json number -q '.[0].number')
        gh pr review --approve $pr_number
