name: Fetch Data

on:
  workflow_dispatch:
  schedule:
    - cron:  '30 11 * * *'

jobs:
  fetch_data:
    runs-on: ubuntu-latest
    env:
      API_KEY: ${{ secrets.ODDS_API_KEY }}
      PROJECT_ROOT: ${{ github.workspace }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run fetch_data script
      run: python src/fetch_data.py

    - name: Commit and push if changed
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        timestamp=$(date -u)
        git commit -m "Automated data update $timestamp" || exit 0
        git push


    
